INSERT INTO HALLS(ID, NAME, CAPACITY)
VALUES (1, 'Hall 1', 30),
       (2, 'Hall 2', 30),
       (3, 'Hall 3', 30);

WITH RECURSIVE HALL1_SEATS(N) AS (
    SELECT 1
    UNION ALL
    SELECT N + 1
    FROM HALL1_SEATS
    WHERE N < 30
)
INSERT INTO SEATS (ID, SEAT_NUM, HALL_ID)
SELECT NEXT VALUE FOR SEAT_SEQ, N, 1
FROM HALL1_SEATS;

WITH RECURSIVE HALL2_SEATS(N) AS (
    SELECT 1
    UNION ALL
    SELECT N + 1
    FROM HALL2_SEATS
    WHERE N < 30
)
INSERT INTO SEATS (ID, SEAT_NUM, HALL_ID)
SELECT NEXT VALUE FOR SEAT_SEQ, N, 2
FROM HALL2_SEATS;

WITH RECURSIVE HALL3_SEATS(N) AS (
    SELECT 1
    UNION ALL
    SELECT N + 1
    FROM HALL3_SEATS
    WHERE N < 30
)
INSERT INTO SEATS (ID, SEAT_NUM, HALL_ID)
SELECT NEXT VALUE FOR SEAT_SEQ, N, 3
FROM HALL3_SEATS;